services:
  - type: web
    name: code-bug-predictor
    env: python
    plan: free
    region: ohio
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: USE_GEMINI
        value: "true"
      - key: DB_PATH
        value: "./bug_predictor.db"
      - key: API_URL
        value: "http://127.0.0.1:8000"
